const creations=[{name:"Le Pavé du Havre",note:"Praliné amande, éclats de grué",tone:"dark"},{name:"La Ganache Maison",note:"Chocolat noir, crème infusée",tone:"copper"},{name:"Le Coffret du Parrain",note:"Assortiment de 24 chocolats",tone:"cream"}];
const bonbons=["Buchette","Baiser d’Ange","Italimo","Rocher","Violette et mimosa","François Ier et salamandre","Praliné à l’ancienne","Pailleté","Feuilletine","Spéculoos","Fleur massepain","Godet or","Orangette et citronnette","Nougat","Praliné amande"];
export default function Home(){return <main>
<header className="topbar"><a className="brand" href="#accueil"><span>Au Parrain</span><strong>Généreux</strong></a><nav aria-label="Navigation principale"><a href="#maison">La maison</a><a href="#savoir-faire">Savoir-faire</a><a href="#creations">Créations</a><a href="#bonbons">Bonbons</a><a href="#visite">Nous trouver</a></nav><a className="visit-link" href="#visite">Le Havre · France</a></header>
<section className="hero" id="accueil"><div className="hero-stamp"><span>Maison</span><strong>APG</strong><span>Le Havre</span></div><div className="hero-copy"><p className="eyebrow">Chocolaterie artisanale · Depuis 1985</p><h1>Le chocolat<br/>en héritage.</h1><p className="hero-intro">Des gestes patients, des recettes franches et le goût des belles choses transmises de génération en génération.</p><a className="arrow-link" href="#bonbons">Découvrir nos créations <span>↘</span></a></div><div className="hero-art"><div className="paper-note">Fabriqué chaque jour<br/>dans notre atelier</div><div className="chocolate chocolate-one"><i/></div><div className="chocolate chocolate-two"><i/></div><div className="chocolate chocolate-three"><i/></div><span className="cocoa cocoa-a"/><span className="cocoa cocoa-b"/><span className="cocoa cocoa-c"/></div><div className="scroll-note">Faire défiler</div></section>
<section className="manifesto" id="maison"><p className="section-index">01 — La maison</p><div><h2>Une maison de caractère,<br/>ancrée au Havre.</h2><p>Au Parrain Généreux cultive une chocolaterie sans artifice. Ici, chaque bonbon est façonné à la main, chaque ganache repose le temps qu’il faut et chaque coffret raconte un peu de notre ville.</p></div><blockquote>« La générosité commence par le choix des bonnes matières. »</blockquote></section>
<section className="craft" id="savoir-faire"><div className="craft-visual"><div className="craft-number">40</div><p>années de gestes<br/>et de gourmandise</p></div><div className="craft-copy"><p className="section-index">02 — Le savoir-faire</p><h2>Du tempérage<br/>à l’écrin.</h2><ol><li><span>01</span><div><strong>Sélectionner</strong><p>Des couvertures de caractère, des fruits secs justement torréfiés et des ingrédients lisibles.</p></div></li><li><span>02</span><div><strong>Façonner</strong><p>Pralinés, ganaches et moulages sont travaillés en petites séries dans notre atelier.</p></div></li><li><span>03</span><div><strong>Offrir</strong><p>Chaque composition est préparée avec soin, pour les petits plaisirs comme les grandes occasions.</p></div></li></ol></div></section>
<section className="collection" id="creations"><header><div><p className="section-index">03 — Les créations</p><h2>Les incontournables</h2></div><p>Une collection courte, vivante, façonnée au rythme des saisons.</p></header><div className="product-grid">{creations.map((item,index)=><article className={`product-card ${item.tone}`} key={item.name}><div className="product-visual"><span>{index+1}</span><div className="bonbon"><i/></div></div><div className="product-info"><p>Création 0{index+1}</p><h3>{item.name}</h3><span>{item.note}</span><a href="#bonbons">Découvrir ↗</a></div></article>)}</div></section>
<section className="bonbon-gallery" id="bonbons"><header><p className="section-index">04 — La collection maison</p><h2>Les bonbons<br/>de chocolat</h2><p>Pralinés, pâtes d’amande, gianduja et confiseries : une première sélection de quinze recettes emblématiques de la maison.</p></header><div className="bonbon-grid">{bonbons.map((name,index)=><figure key={name}><img src={`/images/bonbons/${index+1}.png`} alt={`${name}, bonbon de chocolat maison Au Parrain Généreux`} loading="lazy"/><figcaption><span>{String(index+1).padStart(2,"0")}</span><strong>{name}</strong></figcaption></figure>)}</div></section>
<section className="visit" id="visite"><div className="visit-title"><p className="section-index">05 — La boutique</p><h2>Poussez<br/>la porte.</h2></div><div className="visit-card"><p className="script">Bienvenue</p><h3>Au Parrain Généreux</h3><p>Le Havre, Normandie</p><dl><div><dt>Du mardi au samedi</dt><dd>10h — 19h</dd></div><div><dt>Dimanche & lundi</dt><dd>Fermé</dd></div></dl><a href="mailto:bonjour@auparraingenereux.fr">bonjour@auparraingenereux.fr</a></div><div className="visit-seal">APG</div></section>
<footer><div className="footer-brand"><span>Au Parrain</span><strong>Généreux</strong></div><p>Chocolaterie artisanale au Havre</p><div><a href="#accueil">Retour en haut ↑</a><span>© 2026</span></div></footer>
</main>}
